language: c

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq bison comerr-dev flex libcap-ng-dev libdb-dev libedit-dev libjson-perl libldap2-dev libncurses5-dev libperl4-corelibs-perl libsqlite3-dev pkg-config python ss-dev texinfo unzip netbase
    - mkdir ci-build
    - mkdir coverity-build
    - ./autogen.sh

install:
    - cd ci-build
    - ../configure
    - make

script:
    - if [ x${COVERITY_SCAN_BRANCH} != x1 ]; then make check; fi

compiler: clang

notifications:
    email:
        on_success: change
        on_failure: always


addons:
    artifacts: true
    coverity_scan:
        project:
            name: "heimdal/heimdal"
            description: "Build submitted via Travis CI"
        notification_email: lha@h5l.org
        build_command_prepend: ../configure
        build_command: make
        branch_pattern: coverity_scan
